services:
  - type: Background Worker
    name: teacher-coach-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    autoDeploy: true



    
services:
  - type: web
    name: whatsapp-coach-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    plan: starter
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GREEN_API_ID
        sync: false
      - key: GREEN_API_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.18
